spring:
  kafka:
    bootstrap-servers: localhost:9092
  mongodb:
    uri: mongodb://admin:password@localhost:27017/payment?authSource=admin
  data:
    redis:
      url: redis://localhost:6379

server:
  port: 8080
